# background_image ~/Pictures/Wallpaper/lucario-kitty-bg.jpg

background_image_layout cscaled

background_tint 0.95
background_opacity 0.85
dynamic_background_opacity yes

foreground #d0d0d0
background #0a0e14
selection_foreground #0a0e14
selection_background #3d59a1

cursor #f0c674
cursor_text_color #111111
cursor_shape beam

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

disable_ligatures never

window_padding_width 10
# hide_window_decorations yes

# tab_bar_min_tabs 1
# tab_bar_edge top
# tab_bar_style powerline
# tab_powerline_style slanted
# active_tab_foreground   #0a0e14
# active_tab_background   #3d59a1

shell fish
